services:
  vpngate2socks:
    container_name: vpngate2socks
    build: .
    # 如果Egress出现异常请取消下面这行注释
    #network_mode: "bridge"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "127.0.0.1:1080:1080"
    environment:
      - COUNTRY=${COUNTRY:-}
      - IP_TYPE=${IP_TYPE:-}
      - PROXY_PORT=1080
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
